### ISSUE TITLE
Need to establish initial CLI command, arguments and flags

### ISSUE THREAD

**Issue by benjmarshall** [the-heap/beacon#11]
I think establishing a consensus on the basic commands required along with their arguments/flags is an important next step as it will shape the layout and hierarchy of the tool as it develops.

Some basic command ideas for starters:

- Create a breaking change (beacon create --message "blah blah blah")
- List changes (beacon list)

And some others for further on:

- Initialisation for a new project? (beacon init)
- Some way of viewing/updating configuration info if we need it? (beacon get-config/set-config <config param>)

Anything else?

**Comment by jbydeley** [comment]
I'd love to see the following included in some way:

* Templates (Similar to `git status -s` vs `git status --long`)
* Some way to limit the number of breaking changes you want to see? Over the course of a project I imagine the list of breaking changes could get quite large and I only care about the last 3 or the last weeks?

**Comment by teesloane** [comment]
These are both good points. Thank you for adding your thoughts and ideas @jbydeley + @benjmarshall. @broneks and I have just finished up pairing up on writing a message to Beacon. If anyone is interested in collaborating on it, the branch is currently up for [PR: Work in Progress](https://github.com/the-heap/beacon/pull/12/files)

Here are some quick notes:

1. We decided to just parse a command argument rather than a flag:

> `go run main.go add`

2. This ☝️ will trigger a set of prompts such as the following:

![image](https://user-images.githubusercontent.com/12987958/29149362-9470759c-7d41-11e7-89bf-8a6d49251e9f.png)

3. The prompts will eventually construct a struct of type `Log`.
4. This log gets appended to `beacon_log.json`.

Does this make sense so far? I'm pretty happy with the prompt idea, rather than asking developers for command line flags (which will reduce the need to learn a new api for a tool, and also (hopefully) make's sure all fields get filled our properly.

thoughts? I'm open to new ideas, but I also want this project to move quickly and have it done before end of month. 

Perhaps we can agree on the mvp list of flags, and a "nice to - have" flag / arguments. We can finalize that in the next 12-24 hours or so, and then create a new issue that properly tracks the agreed upon flags / arguments.  Here is what I propose

**MVP command lines**

- [ ] `beacon` -> just prints the 5 most recent changes 
- [x] `beacon add`  
- [x] `beacon all` 

**Possible interesting ideas**
- [ ] `beacon init` 
- [ ] `beacon --update-config` -> maybe this launches the local config file in a text editor?
- [ ] `beacon report` -- maybe something that generates a report? 
- [ ] `beacon --date-range?`

please comment with other ideas!

**Comment by jbydeley** [comment]
Normally I would agree that prompts are great for making sure all the information is filled out but in this case I think if we add the author to the config file then we only need the message filled out. It would be a simplified case to just call `beacon add "Hello, I am a terrible breaking change"` which lends itself to be scriptable later (IE, have a githook that looks for something like `BREAKING` in the commit message and then just calls `beacon add` with the git commit message automagically). 

Thoughts?

**Comment by teesloane** [comment]
This is a great point @jbydeley. Ideally there should only be one thing a user has to do to get the job done - write a `beacon add ...`.

I think we can combine the best of both worlds perhaps:

- there should probably be some kind of `.beaconrc` file as discussed earlier
- the program will look for the file in the root directory, (and maybe check the home directory if it doesn't find one)
- the `rc` will provid a user's `name` `email address` and other necessary information
- _if_ neither exist we can use the new prompt functionality to _build_ the `rc` file in the local directory ... or more so, as part of the onboarding. 

I am leaning toward this `beacon add` idea. I'm going to let this ruminate for a half-day - day (I noticed some of you folks are in very different time zones so I want to give an appropriate amount of time for people to have their say.

also looping in @broneks since we built this out tonight and I want to get your opinion too on these new proposed changes.

**Comment by jbydeley** [comment]
I really like that last step, @teesloane. By checking for our config and then using the prompt if it isn't there, we could use that to add a config with their name and email and not require it later. I've been coding up a proposal for the config file using [TOML](https://github.com/toml-lang/toml) just to get my feet wet and hopefully provide some talking points around possible solutions for it.

**Comment by benjmarshall** [comment]
Agree with the @teesloane and @jbydeley here, some way of having a default name/email is great so that a simple command for a new breaking change just becomes `beacon add "I changed all the things..."`.

I want to suggest also using the default git user name and email the repository or global config if nothing is set in a local .beaconrc. i.e. use the output of `git config --global user.name` and `git config --global user.email`. Possibly this should be combined with the prompt idea so that if we need to prompt the user when they add the first breaking change we can suggest using their git details (if they exist) or they can manually enter something.

**Comment by teesloane** [comment]
Sounds excellent @jbydeley 
Do you have any interest in tackling this over in [this issue?](https://github.com/the-heap/beacon/issues/3). I'd love for you to tackle some or all of this feature if you are up for it. 

There has been some coinciding talk with @benjmarshall as well; and this conversation is starting to stray toward that issue I believe. Here are some questions I have that perhaps you can address:

- [x] can we list the advantages of TOML over a json file or `.beacon_rc` file? 
- example: Golang has parsing built in for Json — but not toml. I want to avoid using unecessary packages if able. What would make toml more powerful / a better choice? 
- [x] what information can we put in a toml / json file? What is the minimum? what is nice to know? 


@benjmarshall I never though of using the git globals for information. That's a great idea. 

I also recommend that we start percolating some thoughts on how much we want to bring to the user's attention — ie the developer experience of using `Beacon`. Do we need to bother them with asking for git config information — or is that something we _should_ be telling them because it's personal information? It's something worth thinking about I believe, but not so important to distract up from building out our functionality.

**Comment by teesloane** [comment]
We ended up choosing a `beaconrc` and to use args over flags for creating and displaying messages.
