### ISSUE TITLE
Refactoring pt 1: where to put things / what functions to make

### ISSUE THREAD

**Issue by teesloane** [the-heap/beacon#14]
Looking for some feedback / input on how we can refactor that will make things nicer in the future.

**Our goal with this refactor is to:**

- learn about errors / error handing
- try and get to know what makes idiomatic Go code (ie. packages, where to assign vars etc)
- Talk about if / how code should be broken out into files (should all custom types live in a file? etc)

**Questions**

- What / should things be broken into seperate files
- should we make a function that is meant for just reading files ? Currently we are reading files in two separate places.. could be a place for a function?
- How do we gracefully handle error handling? We have a function called `checkError` that I borrowed from the [go by example](https://gobyexample.com/) site, but I'm not sure what the idiomatic way of doing this is.
- should file contents that are read into memory be stored in a variable _outside_ of the `main()` function? Does this matter?
  - example;

```
// ============================
// Vars and Constants
// ============================

var beaconLogData BeaconLog

// ...
// ...

func main() {
  //...
  beaconLogFile, err := ioutil.ReadFile("./beacon_log.json")
}
```

where as all the reading / setup for the beaconConfig happens in `main`:

```
func main() {
  // ...
  // ...
	var config beaconConfig

	if err := loadConfig(&config); err != nil {
		log.Fatal(err)
	}
}
```

@jbydeley can you weight in on the above one? I'm not sure which is more go-ish... so whatever works / is consistent, we should probably go for. 

Other ideas for refactoring are welcome!

**Comment by jbydeley** [comment]
Sure, I can weigh in. I've only really worked on personal go projects so I could be way off base here. Whatever style / separation / refactoring we do, we should first consider testability of code. Currently we're at 0% which is fine but moving forward, adding tests would be sweet. 

### What should be broken into separate files?
I haven't worked on large scale go applications but for my personal projects I generally keep them as small as possible. I find it's easier to navigate between files then scrolling all over the place

### Should we make a function that is meant for just reading files?
Yep. I was thinking about tackling that next anyway. This would be a good time to use an interface the Go way. We can create a file loader interface that quacks like `ioutil.ReadFile` and then it makes testing easier.

### How do we gracefully handle error handling?
I'm a fan of [Dave Cheney's Error constant solution](https://dave.cheney.net/2016/04/07/constant-errors). Easy enough to implement our own custom errors. As far as `checkError` I usually don't have one of those methods but again, I've only really done small personal projects so I don't know what is best practice.

### Should file contents that are read into memory be stored in a variable outside of the main() function?
This touches on testing. Global are annoying to test with. I prefer to pass everything in and to use interfaces if mocking is required. That said, I'm up for whatever.

**Comment by benjmarshall** [comment]
My thoughts added here:

**What should be broken into separate files?**
Agree here with @jbydeley, in my limited experience it is easier to err on the side of more files than keep large files with many functions. I have also noticed the trend in the Go world seems to be to group small pockets of related functionality into their own packages. For example already we could feasibly have a package for handling the Log file related stuff and another for config file related stuff. The main.go file then becomes a much simpler piece of code which ties everything together.

**Should we make a function that is meant for just reading files?**
As I touched on above I think we could move towards a package based approach. I believe it is slightly more idiomatic to then move functions which read data into a custom data type into methods that act on that type. In this case we would have a package which provides the log data type and methods to read the log file in order to populate that data type. Similarly we would have a config data type and associated reading method.

**How do we gracefully handle error handling?**
I haven't seen that article before but will try and digest it. I haven't personally used a separate function to handle errors before, I have only ever used the common `if err != nil {blah...}' approach.

**Should file contents that are read into memory be stored in a variable outside of the main() function?**
Agree here about issues with global variables, and I don't think we need them as this is a reasonably simple tool which will probably only do one job at a time. I am finishing up some code for a 'print all' function which actually refactors and removes the global log data variable. I will submit a new issue so we can discuss that aspect more directly in context.

**Comment by teesloane** [comment]
Thanks for jumping in folks! I learned a lot just reading this. Here is a quick summary of my thoughts / directions based on your inputs

- [x] We should move functionality into packages: let's say, go with:
  - [x] Config file package : handle reading / writing / init'ing a `beaconrc`_ Issue: #18 PR: #19 
  - [x] Beacon Log package: _handle reading, writing from the `beacon_log.json` #17 

- [x] Variables should get moved into the main function for easier testing ( I did not know that, thank you!) : note, this is already in the works on a pending branch from @benjmarshall 

- [x] We should figure out a consistent way to handle errors.  I have not read mr Cheney's article yet, nor do I really understand error handling in Go, so if anyone wants to tackle it now, you can, other wise we maybe handle it later in this refactor?

- [x] We should write tests. Definitely. I believe once we have the core mvp of the product down (after the speed of things changing slows down) we should launch into test writing mode for at least the core units. I'm still totally new to this so when the time comes feel free to open an issue if you know how we can tackle it!

The last point is: _when do we all do this?_ 

Today I will be merging [the pr for write-to-file](https://github.com/the-heap/beacon/pull/12/files) _however_ our write to file functionality is not complete. So far, it is half way there by asking for a prompt and creating a new Log struct. 

I think this is a fine place to pause, then merge @benjmarshall 's pending branch (which is a bit of a refactor)... then I think we can do a partial refactor — things are small enough that it prob won't take long if we break it up. I think breaking things into smaller files will be a good win for improve the developer experience going forward.

By the way @jbydeley  and @benjmarshall you both should have write access to the repo; so feel free to directly clone and branch when working if you prefer it to working on a fork :)

ps. Perhaps for this refactor we can making issues for each of the checkboxes above if you want to tackle something, and then I'll add the issue alongside the checkbox so this becomes a master list. If we can try and keep our refactorings to solve one thing at a time, that would be ideal for PRs, but I know that's not always possible.

💯 👍 🎉 

pps. I'll be organizing the issues we have to tackle on a [github project](https://github.com/the-heap/beacon/projects/1) if anyone enjoys using those.

**Comment by teesloane** [comment]
We've hit most of the functionality here in these prs: #24  #19
