### ISSUE TITLE
No example beacon_log.json in repository

### ISSUE THREAD

**Issue by benjmarshall** [the-heap/beacon#9]
When clone this repo and following the instructions to run the program the user is simply greeted with a panic.

An example beacon_log.json should be added to the repo so the user can point the program at something to get it running initially.

**Comment by teesloane** [comment]
This is a good point; and something we didn't really think of. 

Right now we have a hard baked file stored in a dropbox that I can give anyone access too. I think we should just check this file in and load it relatively rather than a hard link to a dropbox file. I will fix this today. 

edit:

the [PR](https://github.com/the-heap/beacon/pull/10) is here if you have time / interest in PR'ing it; it's only a handful of lines :)

**Comment by teesloane** [comment]
Shipped this!
